[package]
name = "sshdeck-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
async-channel = "2"
bytes = "1"
russh = { version = "=0.63.3", features = ["des"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
