[package]
name = "sshdeck-sftp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-channel = "2"
bytes = "1"
russh-sftp = "=3.0.0"
sshdeck-core = { path = "../sshdeck-core" }
thiserror.workspace = true
tokio = { version = "1", features = ["rt", "io-util"] }
